// const GET_SYMBOLS = 'GET_SYMBOLS';

// export default GET_SYMBOLS;

export const GET_SYMBOLS_REQUESTED = 'GET_SYMBOLS_REQUESTED';
export const GET_SYMBOLS_SUCCESS = 'GET_SYMBOLS_SUCCESS';
export const GET_SYMBOLS_FAILED = 'GET_SYMBOLS_FAILED';

export const GET_RATE_REQUESTED = 'GET_RATE_REQUESTED';
export const GET_RATE_SUCCESS = 'GET_RATE_SUCCESS';
export const GET_RATE_FAILED = 'GET_RATE_FAILED';

export const ADD_FAVORITE = 'ADD_FAVORITE';
export const GET_FAV_RATES_REQUESTED = 'GET_FAV_RATES_REQUESTED';
export const GET_FAV_RATES_SUCCESS = 'GET_FAV_RATES_SUCCESS';
export const GET_FAV_RATES_FAILED = 'GET_FAV_RATES_FAILED';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
