const GET_SYMBOLS = 'GET_SYMBOLS';

export default GET_SYMBOLS;

export const GET_SYMBOLS_REQUESTED = 'GET_SYMBOLS_REQUESTED';
export const GET_SYMBOLS_SUCCESS = 'GET_SYMBOLS_SUCCESS';
export const GET_SYMBOLS_FAILED = 'GET_SYMBOLS_FAILED';
